# BitBake for Yocto builds, based on Debian

FROM    debian
LABEL \
 Description="BitBake for Yocto builds. Image based on Debian." \
 MAINTAINER="Thomas Thorne <TafThorne@GoogleMail.com>"
RUN apt-get update && apt-get -y install \
 build-essential \
 chrpath \
 cpio \
 debianutils \
 diffstat \
 gawk \
 gcc-multilib \
 git-core \
 iputils-ping \
 python \
 python3 \
 python3-pip \
 python3-pexpect \
 socat \
 texinfo \
 unzip \
 wget \
 xz-utils

